export type TeamMember = {
  name: string;
  role: string;
  bio: string;
  linkedin: string;
  image: string | null;
};

// User-supplied details. Photos are temporary dummy portraits, not the named people.
// Full biographies supplied by the user; do not infer unconfirmed professional details.
export const teamMembers: TeamMember[] = [
  { name: 'Riz Razak', role: "Founder", bio: "Riz is our Founder, outspoken and provocative, and well known media personality in Sri Lanka. The Sri Lankan-Dutch hybrid, after growing up as a true global citizen, from Sri Lanka to Singapore to the Netherlands and now back in his backyard in Colombo has worn many hats in his life, from E-commerce to Branding to Tech Products; executing startups to scale-ups and bringing order to chaos has become second nature. At DGTL, you could spot him channelling his ever expanding business, tech and marketing acumen, empowering the purpose-driven economy in every possible way. When he’s not trying to better the world in some way, you might catch a glimpse of him in some high-altitude mountain or spotting a rare bird in Sri Lanka.", linkedin: 'https://www.linkedin.com/in/rizrazak/', image: '/assets/team/dummy-1.jpg' },
  { name: 'Lavanga Kapugamage', role: "Digital Marketing Specialist", bio: "Lavanga is a digital marketing specialist - a graduate from the University of Peradeniya with a Bachelor's of Business Administration and with a previous degree in accounting from AAT Sri Lanka. Having worked with blue-chip companies as diverse as Hemas and Dilmah, Lavanga boasts expertise in digital marketing strategy, bringing her insight into Sri Lanka's digital marketing landscape to DGTL.", linkedin: 'https://www.linkedin.com/in/lavanga-kapugamage-a430b7216/', image: '/assets/team/dummy-2.jpg' },
  { name: 'Kasuni Madushika', role: 'Content Strategist', bio: 'Kasuni has a strong digital and creative background. Her experience stems across the fashion, food, hospitality and entertainment industries with an expertise in digital marketing, social media, content creation, and brand communication. Altogether, this brings strategic thinking with an adaptable and insightful creative eye. She has worked across diverse brands and industries, developing a versatile approach to building engaging content and meaningful brand presence.', linkedin: 'https://www.linkedin.com/in/kasuni-madushika-55a4871b0/', image: '/assets/team/dummy-3.jpg' },
  { name: 'Sunera Bandara', role: "DGTL 360 Team", bio: "Sunera is a diverse character having trained for and passed the bar course of England & Wales in 2024. He consulted with Lanka Monthly Digest having helped curate their podcast strategy whilst providing profiles and a geopolitical monthly column. Alongside his initiative to help drive the company forward, he helps facilitate the vision of the company through mind-mapping and strengthening concepts through to execution. When he is not at his office desk, he is writing a novel - his newest piece of spy fiction is due out soon.", linkedin: 'https://www.linkedin.com/in/sunera-bandara/', image: '/assets/team/dummy-4.jpg' },
  { name: 'Rehan Amaratunga', role: "Business Development & Creative Analysis", bio: "Whilst a business development and creative analyst by profession, he is also well known for his role as Richard De Zoysa in the blockbuster 'Rani'. Rehan's creative eye and ability to look at projects with an artistic angle benefits companies who are looking not only to improve their aesthetic game but to find inspiring and enriching ideas that will serve an intuitive and creative focus.", linkedin: 'https://www.linkedin.com/in/rehan-amaratunga/', image: '/assets/team/dummy-5.jpg' },
  { name: 'Nipuna Janaranjana', role: 'AI/ML Engineer', bio: 'Nipuna is an AI/ML Engineer. He has a degree from the University of Sri Jayewardenepura. His focus is the building of LLMs, RAG systems, and scalable microservices with a view to creating SaaS applicability within Sri Lanka. He had started in the International Hospitality Management Institute and the National Science Foundation Sri Lanka. He spends his time taking AI models from their early stages all the way into production - he has a visionary focus on speech synthesis and cloud systems. Away from the desk - Nipuna spends time in nature, around animals and plants to recharge his intellectual curiosity and imagination. He is also fascinated by philosophy and is especially interested in exploring where Buddhist thought meets Western ideas.', linkedin: 'https://www.linkedin.com/in/nipuna-janaranjana-936960285/', image: '/assets/team/dummy-6.jpg' },
  { name: 'Prasad Jayanga', role: "Creative Marketing Specialist", bio: "PJ is a creative marketing specialist with 10+ years of experience in brand and product strategy, event management alongside driving results through intuitive and thoughtful initiatives.", linkedin: 'https://www.linkedin.com/in/prasad-jayanga-34a58336/', image: '/assets/team/dummy-7.jpg' },
  { name: 'Thushan Ekanayaka', role: 'Full-stack Developer', bio: 'Aside from his creative interests and hobbies - photography and chess - Thushan Ekanayaka is a full-stack developer and a graduate of the University of Sri Jayewardenepura and is multiplying his impact in a creative way whilst also enjoying the agentic development frontier. Thushan brings genuine curiosity for AI as well as emerging technologies at this juncture in history. He has a particular interest in the intersection of fashion and technology. He has a versatile command of mobile and web application design and development, blending creativity with technical precision.', linkedin: '', image: null },
];
